apiVersion: apps/v1
kind: Deployment
metadata:
  name: manohar-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu:  "50m"
        ports:
        - containerPort: 3015
---
# service.yaml file to expose the application
apiVersion: v1    
kind: Service
metadata:
  name: manohar
spec:
  selector:
    app: manohar
  ports:
  - port: 3016
    targetPort: 3015
  type: LoadBalancer
    
